# Generated by Django 2.1.7 on 2019-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190216_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='_task_tasks_+', to='tasks.Task'),
        ),
    ]
