# Generated by Django 2.1.7 on 2019-02-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='done',
        ),
    ]
