# Generated by Django 2.1.7 on 2019-03-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_main_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='main_tag',
            new_name='tag',
        ),
    ]
