# Generated by Django 2.1.7 on 2019-03-05 21:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_tag_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='username',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
